[theme]
primaryColor="#003c6f"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#E0E0E0"
textColor="#0E1117"
font="sans serif"

[browser]
gatherUsageStats = false

[deprecation]
showPyplotGlobalUse = false