[theme]
primaryColor="#003c6f"
backgroundColor="#edf6f9"
secondaryBackgroundColor="#5C8383"
textColor="#0E1117"
font="sans serif"

[browser]
gatherUsageStats = false

[deprecation]
showPyplotGlobalUse = false